# Generated by Django 4.0.2 on 2022-02-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointtype', models.TextField()),
                ('gpoint', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '그린포인트목록',
                'db_table': 'greenlist',
            },
        ),
        migrations.CreateModel(
            name='Vehiclepoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointtype', models.TextField()),
                ('gpoint', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '자동차포인트목록',
                'db_table': 'vehiclelist',
            },
        ),
        migrations.AlterModelTable(
            name='carbon',
            table='carbonuser',
        ),
    ]
