# Generated by Django 4.0.2 on 2022-02-03 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_greenpoint_vehiclepoint_alter_carbon_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehiclepoint',
        ),
    ]
