# Generated by Django 4.0.2 on 2022-02-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_delete_vehiclepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonpoint',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greenpoint',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
