# Generated by Django 4.0.2 on 2022-02-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0004_carbonpoint_modify_date_greenpoint_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonpoint',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='greenpoint',
            name='modify_date',
        ),
    ]
