# Generated by Django 4.0.2 on 2022-02-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0005_remove_carbonpoint_modify_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonpoint',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greenpoint',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
