# Generated by Django 4.0.2 on 2022-02-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0006_carbonpoint_modify_date_greenpoint_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonpoint',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='greenpoint',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
