# Generated by Django 4.0.2 on 2022-02-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_alter_question_voter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
